module.exports = {
  extends: [
    'standard',
    'plugin:eslint-comments/recommended',
  ],
  plugins: ['markdown'],
  ignorePatterns: [
    '*.min.*', 'dist', 'output',
    'CHANGELOG.md', 'LICENSE*',
    'coverage', '__snapshots__',
    'public', 'temp',
    'packages-lock.json', 'yarn.lock', 'pnpm-lock.yaml',
    '!.github', '!.vitepress', '!.vscode',
  ],
  overrides: [
    {
      files: ['*.json', '*.jsonc', '*.json5'],
      parser: 'jsonc-eslint-parser',
      rules: {
        'quotes': ['error', 'double'],
        'quote-props': ['error', 'always'],
        'comma-dangle': ['error', 'never'],
      },
    },
    {
      files: ['*.json'],
      extends: ['plugin:jsonc/recommended-with-json'],
    },
    {
      files: ['*.jsonc'],
      extends: ['plugin:jsonc/recommended-with-jsonc'],
    },
    {
      files: ['*.json5'],
      extends: ['plugin:jsonc/recommended-with-json5'],
    },
    {
      files: ['*.yaml', '*.yml'],
      parser: 'yaml-eslint-parser',
      extends: ['plugin:yml/recommended'],
      rules: {
        'spaced-comment': 'off',
        'yml/quotes': ['error', { prefer: 'single', avoidEscape: false }],
        'yml/no-empty-document': 'off',
      },
    },
    {
      files: ['package.json'],
      parser: 'jsonc-eslint-parser',
      rules: {
        'jsonc/sort-keys': ['error', {
          pathPattern: '^$',
          order: [
            'name', 'type', 'version', 'private', 'packageManager',
            'description', 'categories', 'keywords', 'license',
            'author', 'contributors', 'repository',
            'homepage', 'bugs', 'funding',
            'engines',
            'main', 'module', 'browser', 'bin',
            'types', 'typesVersions', 'unpkg', 'jsdelivr',
            'exports', 'files',
            'sideEffects', 'scripts',
            'peerDependencies', 'peerDependenciesMeta',
            'optionalDependencies', 'dependencies',
            'devDependencies', 'bundledDependencies',
            'pnpm', 'overrides', 'resolutions',
            'husky', 'lint-staged', 'simple-git-hooks',
            'config', 'eslintConfig', 'publishConfig', 'workspaces',
          ],
        },
        {
          pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies$',
          order: { type: 'asc' },
        },
        {
          pathPattern: '^exports.*$',
          order: ['types', 'require', 'import'],
        },
        {
          pathPattern: 'scripts',
          order: [
            'dev', 'build', 'generate', 'preview',
            'test', 'typecheck', 'lint', 'release',
          ],
        },
        ],
      },
    },
    {
      files: ['**/*.md'],
      processor: 'markdown/markdown',
      extends: ['plugin:markdown/recommended'],
    },
  ],
  rules: {
    // common
    'semi': ['error', 'never'],
    'curly': ['error', 'multi-or-nest', 'consistent'],
    'quotes': ['error', 'single'],
    'quote-props': ['error', 'consistent-as-needed'],
    'no-unused-vars': 'warn',
    'no-param-reassign': 'off',
    'no-debugger': 'error',
    'no-console': ['error', { allow: ['warn', 'error'] }],
    'no-cond-assign': ['error', 'always'],
    'no-restricted-syntax': [
      'error',
      'DebuggerStatement',
      'LabeledStatement',
      'WithStatement',
    ],
    'no-return-await': 'off',
    'space-before-function-paren': ['error', 'never'],
    'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 0 }],
    'indent': ['error', 2, { SwitchCase: 1, VariableDeclarator: 1, outerIIFEBody: 1 }],

    // style
    'array-bracket-spacing': ['error', 'never'],
    'arrow-spacing': ['error', { before: true, after: true }],
    'block-spacing': ['error', 'always'],
    'brace-style': ['error', '1tbs', { allowSingleLine: true }],
    'camelcase': ['error', { properties: 'always' }],
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': ['error', { before: false, after: true }],
    'comma-style': ['error', 'last'],
    'dot-location': ['error', 'property'],
    'dot-notation': ['error', { allowKeywords: true, allowPattern: '^[a-z]+(_[a-z]+)+$' }],
    'eqeqeq': ['error', 'smart'],
    'func-call-spacing': ['error', 'never'],
    'key-spacing': ['error', { beforeColon: false, afterColon: true }],
    'keyword-spacing': ['error', { before: true, after: true }],
    'no-constant-condition': 'error',
    'no-empty-pattern': 'error',
    'no-extra-parens': ['error', 'all'],
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-useless-concat': 'error',
    'object-curly-newline': ['error', { consistent: true }],
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    'object-shorthand': ['error', 'always', { avoidQuotes: true }],
    'operator-linebreak': ['error', 'before'],
    'prefer-template': 'error',
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': ['error'],
    'space-unary-ops': ['error', { words: false, nonwords: false }],
    'template-curly-spacing': ['error', 'never'],
  },
}
