export * as parserVue from 'vue-eslint-parser'
export * as parserYaml from 'yaml-eslint-parser'
export * as parserAstro from 'astro-eslint-parser'
export { parser as parserTs } from 'typescript-eslint'
export { default as parserJsonc } from 'eslint-plugin-jsonc'
